# Generated by Django 5.1.6 on 2025-02-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='imagedase')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
